Fix NFS install in wso2is

diff --git a/pattern-1/bosh-release/jobs/wso2is/templates/ctl.erb b/pattern-1/bosh-release/jobs/wso2is/templates/ctl.erb
--- a/pattern-1/bosh-release/jobs/wso2is/templates/ctl.erb
+++ b/pattern-1/bosh-release/jobs/wso2is/templates/ctl.erb
@@ -66,12 +66,20 @@ log_debug "Kicking off ctl script as `whoami` with $1"
 
 dpkg -s nfs-common >/dev/null 2>&1
 if [ $? -ne 0 ] ; then
+  chmod 1777 /tmp
+  apt-get update
+  if [ $? -ne 0 ] ; then
+    log_debug "apt-get update failed"
+  fi
   log_debug "Installing NFS Client"
-  sudo apt-get update
-  sudo apt-get install nfs-common -y
+  apt-get install nfs-common=1:1.2.8-9ubuntu12 -y
+  if [ $? -ne 0 ] ; then
+    log_debug "Installing nfs-common failed"
+  fi
 fi
 
 mkdir -p ${NFS_SHARE_SERVER_DIR}
+log_debug "`ls -la ${NFS_SHARE_SERVER_DIR}`"
 
 case $1 in
 
