Refactor bosh release to read conf files as templates and to use a mysql datasource.

diff --git a/bosh-release/jobs/wso2is/templates/ctl.erb b/bosh-release/jobs/wso2is/templates/ctl.erb
--- a/bosh-release/jobs/wso2is/templates/ctl.erb
+++ b/bosh-release/jobs/wso2is/templates/ctl.erb
@@ -85,26 +85,21 @@ case $1 in
     WSO2_IS_HOME=`pwd`
 
     # Here copy all the configurations needs to be replaces the application for ex:lib, conf files
-#conf_file=`ls $JOB_DIR/config/*`
-cp -r ${WSO2_IS_CONFIG}/* ${WSO2_IS_HOME}/
+    cp -r $JOB_DIR/config/* ${WSO2_IS_HOME}/repository/conf/
 
-    # Here add any database driver your application needs for ex:
-    # pushd ${POSTGRES_DRIVER_HOME}
-    # driver_file=`ls postgres*.jar`
-    # cp ${driver_file} ${WSO2_IS_HOME}/lib
+    # Here add any libraries your application needs:
+    cp /var/vcap/packages/mysqldriver/* ${WSO2_IS_HOME}/repository/components/lib/
 
-export local_docker_ip=$(ip route get 1 | awk '{print $NF;exit}')
-   axi2_xml_location=${WSO2_IS_HOME}/repository/conf/axis2/axis2.xml
-if [[ ! -z ${local_docker_ip} ]]; then
-   sed -i "s#<parameter\ name=\"localMemberHost\".*#<parameter\ name=\"localMemberHost\">${local_docker_ip}<\/parameter>#" "${axi2_xml_location}"
-   if [[ $? == 0 ]]; then
-      echo "Successfully updated localMemberHost with ${local_docker_ip}"
-   else
-      echo "Error occurred while updating localMemberHost with ${local_docker_ip}"
-   fi
-fi
-
-
+    export local_docker_ip=$(ip route get 1 | awk '{print $NF;exit}')
+    axi2_xml_location=${WSO2_IS_HOME}/repository/conf/axis2/axis2.xml
+    if [[ ! -z ${local_docker_ip} ]]; then
+      sed -i "s#<parameter\ name=\"localMemberHost\".*#<parameter\ name=\"localMemberHost\">${local_docker_ip}<\/parameter>#" "${axi2_xml_location}"
+      if [[ $? == 0 ]]; then
+        echo "Successfully updated localMemberHost with ${local_docker_ip}"
+      else
+        echo "Error occurred while updating localMemberHost with ${local_docker_ip}"
+      fi
+    fi
 
     $WSO2_IS_HOME/bin/wso2server.sh start
 
